# General settings
if-shell 'if ($env:OS -ne "Windows_NT") { exit 1 }' 'set -g allow-predictions on'
set -g @continuum-boot 'on'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '10'
set -g @resurrect-capture-pane-contents 'on'

# Prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Keys
set -g extended-keys on
set -g extended-keys-format csi-u
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Panes
bind - split-window -v -c "#{pane_current_path}"
bind = split-window -h -c "#{pane_current_path}"
unbind '"'
unbind %
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Plugins - Windows (psmux)
set -g @plugin 'psmux-plugins/ppm'
set -g @plugin 'psmux-plugins/psmux-sensible'
set -g @plugin 'psmux-plugins/psmux-resurrect'
set -g @plugin 'psmux-plugins/psmux-continuum'
set -g @plugin 'psmux-plugins/psmux-theme-onedark'
run '~/.config/psmux/plugins/ppm/ppm.ps1'

# Plugins - Linux (tmux)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'odedlaz/tmux-onedark-theme'
run '~/.tmux/plugins/tpm/tpm'
