set-window-option -g xterm-keys on
set -g default-terminal "screen-256color"
set -as terminal-overrides ',xterm*:Tc'

# Start window index at 1
set -g base-index 1
set-window-option -g pane-base-index 1

# Change prefix to Ctrl-a
set -g prefix C-a
unbind C-b # unbind the default prefix key
bind C-a send-prefix

# set extended keys for pi
set -g extended-keys on
set -g extended-keys-format csi-u

# Enable mouse mode
set -g mouse on
